apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s06ybruou-java-springboot-prod
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/s06ybruou-java-springboot/overlays/prod
    repoURL: https://github.com/rhtap-rhdh-qe/s06ybruou-java-springboot-gitops.git
    targetRevision: main
  destination:
    namespace: rhtap-app-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
